os:
  - linux
language: node_js
node_js:
  - "4"
  - "6"
  - "7"
  - "8"
install:
  - npm install
script:
  - npm run tslint
  - npm run doc
  - npm run build
  - npm run test
after_success:
  - npm run codecov