sudo: required
addons:
  firefox: latest
  chrome: stable
  apt:
    packages:
    - ncftp
os:
- linux
language: node_js
node_js:
- '12'
install:
- npm install
script:
- npm run lint
- npm run build
- npm run test
after_success:
- npm run codecov
- ncftpput -R -v -u $FTP_USER -p $FTP_PASS bcc.beyerleinf.de dist dist/*
env:
  global:
  - secure: oDGc6jllgx891xBPwvYIg3KXwV8p8H+3nhVMSbpgg5CNqJGhS0ldkcpCw2g69gC16Rmugg+535f+NIfSEynMryMKXESdqBDeln1yJEiYbets342qpCD9/x8kNPf6NVTUfohdHu/0kn3hZJe2G7lnrNImMuxR3VtITM4aaVO3bfbjiI5xguNMJl8zhDTSuZL1MhadAe5AHuZcqx7pLWHs6Y/zf8EoUqSLCEjFqEVUuHzjZC5959bbMfI3jkufq+KMElJrAK5jE1TgnAZxZYpDFYci7g6KqBogoALKAHHo/0cpJb4a7C0EnLjN/kUxcopKG75HdU5tXm3QIthQUZa/yYbQraBPqAwaRWFNvctBPleleLk6NtUVOrLBEy5cnewpXYpCFkeXrZCX8qZVwdLIhQrYgQoX0HC72kXydF/FbMWz3XPcQUVRx55uowPGwJtNmWP5u/dff0SPziJwrvvGvxolsbf5SywRJyni/90LTUnR8nqYBK93MAhtoLRGjWNLbrACx6d4NfXDDNLPq/eI76V332eDsYZV5gCVKWv6awo3ARIGy99GgG3d+XzKIvryT2UihzT6awZYRPYsBqZ16BTcBU30hIUUKCEcPYwGGDYwqZlim8UVb5gAsc4U1cTXj/QNID8MDYj796k8p9LVUcki55CcAhM3U73IkS8nxHk=
  - secure: POGHEEBTOIe4sxgLnyhiXL5um15izjyXBsjW/3ebVLpenpmwwvvCgjDRWU4eNCZT9HPdq3QWH7CiLLZuboh8Ux7NkgHQlAt9bBU3Vyyp2BaYn1x8BNUycw9vkn1LMxji7ndVzwTmWWJl/DtaeuRi23u8raa2MpzCOQeP5AXp1fFeSq4a0CqdTZ/p1XryaRaOUKsC66uG2EAO2dYU905tBYMscGUqyU5TmWOLNl/btrcWAcv2R+rQ6ua4hfmmRhA8umvftxU4/ZTDvCVbi8o5m5AsjMR0TDeG9DsIlTlkRmEP9w0Zm++UFNnohQ14ax2ki3JKAgmz61ZYj/jufbISJv49Humh12KCAGOcdxyz7EPqpSzOvmtK2EY49fKT7pB9sy/jTbuV6lKidqiUuRe5QoN+Uqe/yO6gyYi08eG3xz3HrKxCmrUP2/ZpRADFhWIi/rn1eU6alJSLQrsoYNRbn+n2haKcsljk2SpXu/llSzDPtdiLs55pNzkHUpQjDTnj2f2KPlxL5Kx/2wHMSH0OgtpL6solzJHJeTgjHRlxELrunwaMoK1Yi3XYXqXfOWyV3EB91flpFcx6dEQ4mvhOonOJv6PDs6wTNIjCP/tRc+FZDoC+6BqOBhUcRQUiA1GhZ3Ggf5ViHtePdpXiRDWJFgxJIaaneVZvtIksZs9Qz/U=
