sudo: required
addons:
  firefox: latest
  chrome: stable
  apt:
    packages:
    - ncftp
os:
- linux
language: node_js
node_js:
- '8'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install
script:
- npm run tslint
- npm run build
- npm run test
after_success:
- npm run codecov
- ncftpput -R -v -u $FTP_USER -p $FTP_PASS ftp.strato.de dist dist/*
env:
  global:
  - secure: JDjjLSSbZlO3DK8CnNWqha/+DkeHpq//bTzLAEucNj7teNwsBrtI2KSgIDBqR/7t5Rm5tH6079HElDSUSUBXnV+mWb9zhFQgQsX8tpVoxuCbYpmpvO2Kf7aJbgkSrb6voUJHs7asS5LXKzHZdTHLYwBUCBUbozuDLZL3HTE5qD8bdA+DkLx2LivsJM58Poih0dlYnNlgNd4m08ADdGQ9WW/XVRaJtL2tjMpLB1g5MvGJdm0ClEkQT0kCjnfAlY55WRL/OeEHnYgZv0w1RHs5aJ40ePl8nMBk8a9Z2Seay5itInsXu5czpIMruZzRZk8tYUpNwuOu4YegXypehZIaHBsM5Kjfev+ZabW3ytiPWm7A2pAhP5GJAFuk7Qm7YECLWjVnjjBxg0xxsEY0cg/z3oc15tXdgJ5MnOcPSJqZ/V377VCyhFI2nVUPxHBcEfE7/l5v7jTqgABKvmrUhbBKYX+hpRJk26vk37PVQt/S5CxNfXo2G+0n+oJUnt9zf+Iw6rbbaSnKGsRXK8szRAqDtNrIt44udGOw1xEVVTo7Pnlp9DrPKKNO4KeVU9c6o68cOn7fHThLa5uSlGDN4ATMPpWwfimioly/5MMjkYe5UZeyPVAnKID16VjYmwYwnZDLrmmIoKGTgIkr25MhF1j7L5BbK5YleWBcq4ZYZaeQlXM=
  - secure: ePrhDD6xm9g7IMqxjJ4IUqX+q55Gve9YkyTWZISbCFlWTghOzR1TsVCFRrpFFQ3U1fN8xnLm6w66Ns6KovkuKfX+NchkK8Tz3Dr1yEEnMfO9Ew48NfIy/WY9wGGdwLl8brqJZziixzSN8nU5aBwoYnJxs61yXl6T1zBRLqX2NgZ7WxmoygHRfQ0WNMdyuo5tDXmwVNKvsuAQZOpVcBxN9phqw9QLLilB79/IfRzTlfRLb2R0mk9igABLU2u5WXLpPPSbl1zAVhJj16wM2LmhuRrbdXYEpRHzso8agLnom9GTVSMEvg/tgZRvMlCjLJ2dZxuQ05h4FfWosRp+MbefALR4wNhdcxdIz1bzU28eqH+sBHlw6PEoenCRyYQgELTa//4LVwINwxULQaNfhBuKw4jIrzRCig0slxtedN/qh5dldI8sB7XQrezZVdl5+KZ5ir5q8zoAlSDjvXA9cMaDb2yxuRkZX8LnvAw+hyRz3gE41T7Q8XhYTOtr3rnjU4/ERvKVdBQT6DGjvi66y4kMVJaOyhmCBA8FT0ZHAMI7NBo3ABfXg2QzbA2uaAqD3voHFq7jnX7YdsXj8CWykBHO86fbhu//Yrqz1zWpdoz5kEdoKkW/3HV4inudwXrvWjmZtIA3p4rd7e9OxHWExblUDRo09CPBvwN42DH7EBMpLZM=
