sudo: required
addons:
  firefox: latest
  chrome: stable
  apt:
    packages:
    - ncftp
os:
- linux
language: node_js
node_js:
- '8'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install
script:
- npm run tslint
- npm run build
- npm run test
after_success:
- npm run codecov
- ncftpput -R -v -u $FTP_USER -p $FTP_PASS ftp.strato.de dist dist/*
env:
  global:
  - secure: m8xdtwyDWEubzi/O+a2cJg1NgjNkbZuzvPqpbx0XoY83+O75H/EGV11clAhss4TwzV5xeO7UXZtSKyiJR0JEZGjI5GvGe1fxX2UfG2b2qVa4Kd73lwQHRXbetLqnVimt3bDgFgQlcYa/drywgx66M/Ek0wINsclfOAn4RZ1ejtdMYtE/kABdpK2ExlvbLsLs4N+/5Rj94NiUE/8wZr3zMahs9gdPn0DGOukK04O6Fu7YPNvWVmFH4Dk/CKCoJLNJhS9pZp6o9ZGCHtSu39sz6kw933/sF0Hlbe7i86UP5CHgXQQwM0EJUETHoZc1Urrlphn/koNX9lM7UPEgJCwXPZ3tY3pkCnw9AMwtUaGNSPDHszJj6dzbWKcFBuP3LxP28CFDMW/nFeEkOKAUYmPUQtEtaRNc19SdjItSKadZhjFxPCZ8DBTJV4+nWbZCxk31dDY11fWIJLiSxall0RJiYmGs+dmrm2NSDi/ZGXP0qSFdl/wqL67VP/ZH20Y6N1Am+Jf2U7Ir+gCHNBuXC8dz+K0eaBteXzANLKqkJRmNMfPv+bkzGTZydiflOe3U5AHcBV8MojVTyhxDuEDvt3TnTPgo+tFJq5JMeSXfphKFKc7jHspRa1q7/P/2XQ6gntMXEuEyadqlIAY+kmQzj1Hawv55q2LO1I1i5KgTbgiy2TE=
  - secure: h5Knq0kwN0HMHCSYTZMA1zSnzm7eZNMMoK3RCWEPPJgiS6z8+Wfd9EM7fE5VCCcf4ZRF3q+SmTu17cmvGq+1LXRdvtF/OTXEscl92aeh3nTwuxcY2lQYdXoLm4/qvJGyNNCR9aPftucKn5MIJM+FAwV3h8MNrgtxuyM0Bf+DIhKKrfTGo8jasmd4RHpz8Nygpd0plFDfsLaq1ImUaNoMK0zTZ7tijXPn0oS32h87ziPKISAq87MzpEYCNcKmRuWMKPopYhbSz5WSVdjziXNwSXzCpkTM6h7LCQFFixWcdT7+uCMjmVu6018mOquK+LbvfDCVOs6h3UEBWWqUiSx0zF4FkLAkCHXOYvx3V4n6bKRAAuR6PZY4dy8pl4eZQb264/v4vtmvrq4YjR0GtnbRUwQbJbzIDNcFnTg4oJPSMTlJQ8vQe+PoTW6sMi1neOl1m0/UPj6C6jmc7nPNUo9GJSZNYJbIuCRp7V3k02Mq+IeSDU1K4lkIxOvoZcBCIhRhCMeZnKTLTg2s3VrEIeiIouo/C+zE4+Fbk2PDo+TAdQKqDAh/coLyfW27ZN5m2BrgawaX6sE17/TamxWviF0MZK9FBxXmvILp0bFZbZxr5ZyMm36TiF8SHTZt9U6N0sNNMmyrhSslEvijHY9nYlAXFCp0EbonDIdBzh5gRmVtgoM=
